version: "3.9"
services:
  mysql:
    image: "mysql/mysql-server:8.0"
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - net
    environment:
      MYSQL_DATABASE: "todoApp"
      MYSQL_USER: "todo"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: '%'
networks:
  net:
    driver: bridge
volumes:
  mysql: 
  